---
# tasks file for K8s_master

- name: Configuring YUM Repo For K8S Services
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgcheck: 1
    repo_gpgcheck: 1
    enabled: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  register: a
- debug:
        var: a

- name: Installing softwares for K8s master
  package:
    name: "{{item}}"
    state: present
  loop:
    - kubeadm
    - iproute-tc
    - docker
  register: b
- debug:
        var: b
- name: Starting all the services
  service:
    name: "{{item}}"
    state: started
  loop:
    - docker
    - kubelet
  register: c
- debug:
        var: c
- name: Changing the CGroup driver
  copy:
    dest: /etc/docker/daemon.json
    content: |
            {
            "exec-opts": ["native.cgroupdriver=systemd"]
            }
  register: d

- debug:
        var: d

- name: Restarting Docker services
  service:
    name: docker
    state: restarted
  register: e
- debug:
        var: e

- name: Update config file for k8s
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  register: g
- name: Restarting sysctl
  command: "sysctl --system"
- name: Slave Joining the cluster
  shell: "{{ token }}"
  register: i
- debug:
        var: i
