apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlrs3
spec:
  replicas: 1
  selector:
    matchExpressions:
    - {key: env,operator: In,values: [dev]}
  template:
    metadata:
      name: mysql
      labels:
        env: dev
    spec:
      containers:
      - name: "mysqlcont1"
        image: "mysql:5.6"
        env:

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
               secretKeyRef:
                 name: mysqlsecret
                 key: mysqlpass


        - name: MYSQL_DATABASE
          valueFrom:
               secretKeyRef:
                 name: mysqlsecret
                 key: mysqldb

          
        - name: MYSQL_USER
          valueFrom:
               secretKeyRef:
                 name: mysqlsecret
                 key: mysqluser

        - name: MYSQL_PASSWORD
          valueFrom:
               secretKeyRef:
                 name: mysqlsecret
                 key: mysqlpass


