---
# tasks file for K8s_master

- name: Configuring YUM Repo For K8S Services
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgcheck: 1
    repo_gpgcheck: 1
    enabled: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  register: a
- debug:
        var: a

- name: Installing softwares for K8s master
  package:
    name: "{{item}}"
    state: present
  loop:
    - kubeadm
    - iproute-tc
    - docker
  register: b
- debug:
        var: b
- name: Starting all the services
  service:
    name: "{{item}}"
    state: started
  loop:
    - docker
    - kubelet
  register: c
- debug:
        var: c
- name: Changing the CGroup driver
  copy:
    dest: /etc/docker/daemon.json
    content: |
            {
            "exec-opts": ["native.cgroupdriver=systemd"]
            }
  register: d

- debug:
        var: d

- name: Restarting Docker services
  service:
    name: docker
    state: restarted
  register: e
- debug:
        var: e


- name: Pulling images for master services
  command:
    cmd: kubeadm config images pull
  register: f
- debug:
        var: f

- name: Update config file for k8s
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  register: g
- name: Restarting sysctl
  command: "sysctl --system"
- name: Initializing Kubeadm
  command: "kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=Mem --ignore-preflight-errors=NumCPU"

- name: Creating .kube Directory
  file:
    path: $HOME/.kube
    state: directory

- name: Copying Config File of K8S Master to HOME Location
  command: "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
  register: k
- debug:
        var: k

- name: Changing Ownership
  shell: "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Setting Up Overlay Network
  command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
- name: Generating Token
  shell: "kubeadm token  create  --print-join-command"
  register: token
  ignore_errors: yes
- debug: 
    var: token.stdout_lines

